from .draw_svg import solve as solveDrawSVG
from .draw_triangle import solve as solveDrawTriangle
from .lift_peg_upright import solve as solveLiftPegUpright
from .peg_insertion_side import solve as solvePegInsertionSide
from .pick_box import solve as solvePickBox
from .pick_cube import solve as solvePickCube
from .place_sphere import solve as solvePlaceSphere
from .plug_charger import solve as solvePlugCharger
from .pull_cube import solve as solvePullCube
from .pull_cube_tool import solve as solvePullCubeTool
from .push_cube import solve as solvePushCube
from .stack_cube import solve as solveStackCube
from .stack_pyramid import solve as solveStackPyramid
